### ISSUE TITLE
mb makehashes crash (because of zsync feature?)

### ISSUE THREAD

**Issue by lrupp** [openSUSE/mirrorbrain#22]
From https://github.com/poeml/mirrorbrain/issues/176

Activating zsync in the Mirrorbrain configuration and run the following to get the zsync "file" done:
`mb makehashes /var/www/download.kiwix.org/ -v --force -t /usr/share/mirrorbrain`
crashes.

Moving the chunk size to 4MB works partly, but mb makehashes still crashes with a file of 200GB.

**Comment by andrii-suse** [comment]
The error looks like pure memory allocation problem: I experimented with 100G file : the zsums column needs to store 236M - it is passed to postgres as hex, so around 500M.
With 200G file it will try to pass ~1G hex string, so can definitely meet the error from the ticket.

Proper solution may be trying to update zsums in batches instead of one go and probably pass binary data directly to postgres instead of hex. Using much bigger block size is an option as well - current 4K is way too small for 200G files.

**Comment by darix** [comment]
maybe we should just introduce a size limit for such things.

**Comment by mlschroe** [comment]
I hope that you're aware that libzypp does not use the zsync column? Why would you want to enable it for opensuse?

**Comment by andrii-suse** [comment]
> Why would you want to enable it for opensuse?

I don't. opensuse branch is where all changes go in at the moment

**Comment by darix** [comment]
master branch stays in the state of peter's original code.
