### ISSUE TITLE
apt-get reports wrong file size for cri-o_1.23.2~0_amd64.deb in provo-mirror.opensuse.org

### ISSUE THREAD

**Issue by andrej-gomozov** [openSUSE/mirrorbrain#71]
Is there a sync issue?
The error is
```
Failed to fetch https://provo-mirror.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.23/xUbuntu_20.04/amd64/cri-o_1.23.2~0_amd64.deb  File has unexpected size (19918280 != 19918648). Mirror sync in progress? [IP: 91.193.113.70 443]
Hashes of expected file:
    - SHA256:5ce43444c74607d6c8ab1e3926faf12c0467d18dd07fc5eb5109a5b5d0b09a3e
    - SHA1:04a8f15647da9164ac9c3c74fd3ee05ec80a7af3
    - MD5Sum:ba2d52c234f0f2041a8b946818081b86
    - Filesize:19918648
```

**Comment by darix** [comment]
More likely this is a bug in the debian package building in devel:kubic:* they need to enable passing release tag from the OBS into debian packages.

**Comment by andrej-gomozov** [comment]
@darix i opened issue on OpenSUSE and seems like this is rsync problem which is running for more than a week. See https://progress.opensuse.org/issues/109217
is this something can be checked and fixed to complete the sync? 

@andrii-suse FYI

**Comment by darix** [comment]
this needs to be fixes in the debian build description of the devel:kubic project it is not a mirroring problem.

**Comment by andrej-gomozov** [comment]
@darix how come that repository download.opensuse.org has no issues with that Debian package and only provo-mirror.opensuse.org has such problem?

**Comment by darix** [comment]
the problem is that the package was rebuilt and the release number was not updated. There is a flag that one can set in the .dsc file which would trigger the update of the releasenumber. with a rebuild you can get slightly different binary packages which have slightly different checksums which lead to the issues you are seeing. the proper fix is to set that flag in the dsc file.

hth.
